#!/bin/sh

if [ ! -d /dev/shm ]
then
	echo "Creating /dev/shm..."
	mkdir /dev/shm
	chmod 777 /dev/shm
fi

touch /dev/mdev.seq
#sysctl -w kernel.hotplug=/sbin/mdev
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
mdev -s

#
# We might have mounted something over /dev, see if /dev/initctl is there.
#
if test ! -p /dev/initctl
then
        rm -f /dev/initctl
        mknod -m 600 /dev/initctl p
fi

