#!/bin/sh

# Stop all init scripts in /etc/rc6.d
# executing them in numerical order.

for i in /etc/rc6.d/K??*
do
	echo "Stopping $i"
	$i stop
done

# Terminate all processes before reboot to try to avoid risk that nvram is not unmounted

killall5 -TERM
sleep 5
killall5 -KILL
