#!/bin/sh

if [ -e /proc/sys/fs/mqueue ]
then
	mkdir -p /dev/mqueue
	mount -t mqueue none /dev/mqueue
fi

# Start all init scripts in /etc/rcS.d and /etc/rc5.d
# executing them in numerical order.

for i in /etc/rcS.d/S??* /etc/rc5.d/S??*
do
	echo "Starting $i"
	$i start
done
