
# ----------------------------------------------------------------------------

RDK_RELEASE ?= "9999"

LGI_RDKB_GIT ?= "git://github.com/lgirdk"
LGI_RDKB_GIT_SUFFIX ?= ".git"
LGI_RDKB_GIT_PROTOCOL ?= "https"
LGI_RDKB_GIT_EXTRAOPT ?= ";branch=ofw"

# ----------------------------------------------------------------------------

LGI_UI_GIT ?= "git://github.com/lgirdk"
LGI_UI_GIT_SUFFIX ?= ".git"
LGI_UI_GIT_PROTOCOL ?= "ssh"
LGI_UI_GIT_EXTRAOPT ?= ";branch=ofw"

WEBUI_OFW_REPONAME ?= "webui-ofw"

# ----------------------------------------------------------------------------

BB_SRCREV_POLICY ?= "cache"

# ----------------------------------------------------------------------------
